name: sscs-case-loader
description: SSCS Case Loader
home: https://github.com/hmcts/sscs-case-loader
apiVersion: v2
appVersion: "1.0"
version: 0.0.30
maintainers:
  - name: HMCTS SSCS Team
dependencies:
  - name: job
    version: 1.1.5
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
