job:
  image: 'https://hmctspublic.azurecr.io/sscs/case-loader:latest'
  schedule: "0 0/4 * * *"
  aadIdentityName: sscs
  ingressHost: sscs-case-loader-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
      - idam-api
      - idam-sscs-systemupdate-user
      - idam-sscs-systemupdate-password
      - sscs-s2s-secret
      - s2s-micro
      - idam-s2s-api
      - ccd-api
      - idam-sscs-oauth2-client-secret
      - idam-oauth-user
      - ccd-jid
      - ccd-tid
      - sftp-dir
      - sftp-user
      - sftp-host
      - sftp-port
      - gaps2-service-sftp-private-key
      - name: app-insights-connection-string
        alias: app-insights-connection-string
  environment:
    CORE_CASE_DATA_JURISDICTION_ID: SSCS
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    IDAM_API_JWK_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/jwks
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IGNORE_CASES_BEFORE_DATE: 1017-07-01
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_SSCS: INFO
    ROOT_LOGGING_LEVEL: INFO
global:
  jobKind: CronJob
